"""create chat table

Revision ID: 43d1f68491a5
Revises: a51f18111fc7
Create Date: 2023-04-05 20:39:50.175582

"""
from alembic import op
import sqlalchemy as sa
from app.utils.common import get_db_now_func


# revision identifiers, used by Alembic.
revision = '43d1f68491a5'
down_revision = 'a51f18111fc7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('end_time', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('status', sa.Enum('start', 'in_progress', 'ready',
                                                'complete', 'cancelled', name='status'), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text(get_db_now_func()), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text(get_db_now_func()), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_chat_sessions_user_id'),
                    'chat_sessions', ['user_id'], unique=False)
    op.create_table('chats',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('chat_session_id', sa.Integer(), nullable=False),
                    sa.Column('message_text', sa.String(), nullable=True),
                    sa.Column('created_by', sa.Enum('user', 'bot',
                                                    name='createdby'), nullable=False),
                    sa.Column(
                        'question_id', sa.Integer(), nullable=True),
                    sa.Column('option_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text(get_db_now_func()), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text(get_db_now_func()), nullable=True),
                    sa.ForeignKeyConstraint(['chat_session_id'], [
                        'chat_sessions.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_foreign_key(None, 'chats', 'options', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    # ### end Alembic commands ###
